Create library and add install
ECP-copa/HACCabana pull request #3
Opened 2023-01-24 19:38 UTC by streeve

Also allow CXX standard newer than 14

2023-02-02 19:11 UTC, junghans commented on src/CMakeLists.txt
> +file(GLOB HACCABANA_HEADERS GLOB *.h)
```suggestion
file(GLOB HACCABANA_HEADERS *.h)
```

2023-02-02 19:12 UTC, junghans commented on src/CMakeLists.txt
> +install(TARGETS HACCabana DESTINATION lib)
```suggestion
install(TARGETS HACCabana DESTINATION ${CMAKE_INSTALL_LIBDIR})
```

2023-02-02 19:14 UTC, junghans requested changes
Maybe we should add an export as well.

2023-02-09 19:19 UTC, streeve commented
@junghans ready for review any time

2023-02-09 19:27 UTC, junghans approved these changes

2023-02-09 19:44 UTC, streeve commented
@steverangel @adrianpope are you guys good with these changes? Should just make the build a little more robust

2023-02-09 19:58 UTC, steverangel commented
I think this all looks fine.

2023-02-09 20:01 UTC, merged